### ISSUE TITLE
Implement 1-wire control?

### ISSUE THREAD

**Issue by unreality** [jaroslawprzybylowicz/fuji-iot#18]
First off, thanks for working on this and decoding the protocol for the Fujitsu units

Do you have any plans to implement/design a circuit that would allow the Pi to use the 1-wire protocol that the Fuji communications pcb exposes? Perhaps an alternative HAT that takes in the 12v 3-wire and comms with the daemon? (although maybe the 3-wire doesnt supply enough power to let the pi run correctly?)

**Comment by jaroslawprzybylowicz** [comment]
Interfacing with 3-wire cable shouldn't be hard. The data wire is effectively half-duplex system with AC unit being the master.
The conversion is doable with an op-amp and a couple of discreet components. Software does not need to be changed for this.

As you pointed out, more problematic piece is power supply . Raspberry PI Zero spec states maximum rating of 1.2A @ 5V which, even with high efficiency step-down converter, results in about 600mA @ 12V. That may be a bit too much for the standard converter built into the AC communication module.

It is likely better to utilize some low power IoT platform for this request. I have built this package using Raspberry Pi because it was very handy during debugging and I had it in my drawer. It is sub-optimal though. Somebody already asked about ESP32 in #17. I can help get it done, but need to pair with somebody willing to test it out (my AC does not offer 3-wire interface out of the box).

**Comment by unreality** [comment]
If you have a circuit diagram to convert the 1-wire into RX/TX lines, I'd be happy to build it and try porting to ESP32

**Comment by unreality** [comment]
the 3-wire interface should work with this library, just use a LIN transceiver to split the rx/tx
